export const HOUR_TOPICS: Record<number, string> = {
  1: "Diagnostic + Exam Map & Distractor Literacy",
  2: "Context Window Management",
  3: "Batch Processing & Extraction Quality",
  4: "Structured Outputs (JSON Mode)",
  5: "Tool Calling Mechanics",
  6: "Tool Calling Patterns",
  7: "Week 1 Consolidation + Mini-Mock",
  8: "MCP Integration & Configuration",
  9: "MCP Servers: Tools, Resources, Prompts",
  10: "Tool Interface Design & Structured Errors",
  11: "Error Propagation & Provenance in Multi-Agent Systems",
  12: "Agent Pattern: Orchestrator-Workers",
  13: "Agent Pattern: Evaluator-Optimizer",
  14: "Week 2 Consolidation + Mini-Mock",
  15: "CLAUDE.md Hierarchy & Path-Scoped Rules",
  16: "Slash Commands, Skills & Plan Mode",
  17: "Guardrails: Multi-Layer Defense",
  18: "Escalation Design & Confidence Calibration",
  19: "Claude Code in CI/CD & Iterative Refinement",
  20: "Prompt Engineering: Explicit Criteria & Few-Shot",
  21: "Multi-Agent Orchestration (Hub & Spoke)",
  22: "Session Management & Workflows",
  23: "Full Mock Exam #1 + Remediation",
  24: "Full Mock Exam #2 + Final Review + Exam Strategy",
};
