export type QuestionSeed = {
  slug: string;
  conceptSlug: string;
  domain: string;
  stem: string;
  options: Record<string, string>;
  correctKey: string;
  distractorReasons: Record<string, string>;
};

export const QUESTION_SEED: QuestionSeed[] = [
  {
    slug: "model-selection-router-haiku",
    conceptSlug: "model-selection",
    domain: "Agentic",
    stem: "A customer-support agent receives 8,000 chats per hour. The first step is routing each chat to one of 12 specialist queues (refund, shipping, technical, etc.). You're currently using Opus for routing and your p95 routing latency is 3.4 seconds. Cost is also blowing past budget. Which change most effectively addresses both issues without sacrificing routing accuracy?",
    options: {
      A: "Switch the router to Haiku and add a small set of routing examples in the system prompt",
      B: "Keep Opus as the router but enable prompt caching on the large system prompt to bring the per-chat cost down",
      C: "Move routing to Sonnet as a middle-ground model and raise max_tokens so it has more room to classify cleanly",
      D: "Keep Opus as the primary router but add a regex-based classifier fallback that fires whenever Opus exceeds the latency budget",
    },
    correctKey: "A",
    distractorReasons: {
      A: "Correct. Routing is a classification task where Haiku with good examples is faster and cheaper while maintaining accuracy.",
      B: "Caching helps cost but not latency much; Opus is still the bottleneck for routing speed.",
      C: "Moving to Sonnet is a half-measure that doesn't fully address either cost or latency at scale.",
      D: "Adding a regex fallback introduces brittleness and doesn't fix the root cause of using too heavy a model.",
    },
  },
  {
    slug: "tool-calling-termination-stop-reason",
    conceptSlug: "agentic-loop-termination",
    domain: "Agentic",
    stem: "Your agent has a tool-use loop that sometimes terminates after one tool call and sometimes runs through 40+ before stopping. Your loop's exit condition is `if \"done\" in response.content.lower(): break`. The on-call engineer wants this fixed today. What change most effectively addresses the root cause?",
    options: {
      A: "Add a system prompt instruction telling the model to say \"I am done\" only when it is genuinely finished with the task",
      B: "Switch the termination check to `response.stop_reason == \"end_turn\"` and add an iteration cap as a backstop",
      C: "Add richer tool descriptions so the model has enough information to decide on its own when the work is actually complete",
      D: "Increase max_tokens so the model always has more room to reason its way to a natural stopping point on each turn",
    },
    correctKey: "B",
    distractorReasons: {
      A: "This doubles down on the same broken approach — parsing text output is the bug, not the phrasing.",
      B: "Correct. Parsing text is the bug. Check the structured field. The iteration cap is a defense-in-depth backstop.",
      C: "Tool descriptions affect tool selection, not loop termination; tangential to the root cause.",
      D: "More tokens does not fix a broken termination check; the model isn't running out of space.",
    },
  },
  {
    slug: "mcp-vs-skill-trigger-order",
    conceptSlug: "skill-vs-tool",
    domain: "Claude Code",
    stem: "Your team has built an MCP server exposing `search_kb`, `get_document`, and `summarize_section` tools. You also have a Claude Code skill at `~/.claude/skills/legal-research/SKILL.md` describing a workflow for legal research. A user asks \"find precedent for non-compete enforcement in California.\" What is the correct understanding of how these two layers interact?",
    options: {
      A: "The MCP server triggers first, because registered tools always take priority over skills whenever both could match the request",
      B: "The skill is purely documentation for humans; the MCP tools always fire on their own regardless of whether the skill is present",
      C: "The skill and the MCP tools both fire in parallel, and the host merges their two separate result streams into one response",
      D: "The skill description matches the request first; once active, the skill's workflow invokes the MCP tools as it needs them",
    },
    correctKey: "D",
    distractorReasons: {
      A: "This reverses the layer order — skills are model-side workflow descriptions selected by description match, they layer above tools.",
      B: "Skills are not purely documentation; they are active workflow descriptions that guide how the model proceeds.",
      C: "Skills and tools do not fire in parallel; the skill activates first and then orchestrates tool calls.",
      D: "Correct. Skills are model-side workflow descriptions selected by description match. Tools (including MCP tools) are invoked from within the workflow when needed.",
    },
  },
  {
    slug: "guardrails-pretooluse-hook",
    conceptSlug: "guardrails",
    domain: "Agentic",
    stem: "Your agent must never process refunds over $500 without human approval. The CTO has reviewed three proposals. Which one ships?",
    options: {
      A: "Add a line to CLAUDE.md instructing the agent never to process refunds over $500 without explicit human approval first",
      B: "Add the no-refunds-over-$500 rule to the system prompt, reinforced with three worked examples of the correct behavior",
      C: "Add a PreToolUse hook on process_refund that denies when amount > 500 and emits a human-review request",
      D: "Train a classifier to detect refund requests above $500 in user messages and prepend a warning to the system prompt",
    },
    correctKey: "C",
    distractorReasons: {
      A: "CLAUDE.md instructions are guidance, not enforcement — they can be drifted, jailbroken, or routed around.",
      B: "System prompt rules are guidance; they can be overridden by clever user input or model drift.",
      C: "Correct. Programmatic interception is enforcement. The other three are all variations of prompt-as-guardrail.",
      D: "A classifier that modifies the system prompt is still a soft guardrail — it doesn't prevent the action programmatically.",
    },
  },
  {
    slug: "agent-pattern-orchestrator-decomp",
    conceptSlug: "agent-pattern-orch",
    domain: "Agentic",
    stem: "You're building a code-review agent. It must analyze a 200-file PR, flag issues in each file locally, then identify cross-file consistency problems. You're seeing degraded quality when the agent tries to do both in one pass — it misses subtle cross-file issues. Which architectural change most effectively addresses this?",
    options: {
      A: "Increase the model's context window allocation and pass all 200 files in a single prompt so it can see everything at once",
      B: "Switch the single-pass agent to Opus so it has the reasoning capacity to handle all 200 files together in one shot",
      C: "Decompose into two passes: per-file subagents for local issues + a separate integration pass for cross-file analysis",
      D: "Add a longer system prompt with explicit instructions to check both per-file issues and cross-file consistency problems",
    },
    correctKey: "C",
    distractorReasons: {
      A: "Attention dilution across 200 files is the problem; more context window makes it worse, not better.",
      B: "Opus throws resources at a structural problem without changing the architecture; still suffers attention dilution.",
      C: "Correct. Orchestrator-worker decomposition fixes attention dilution structurally — per-file workers + a separate integration pass.",
      D: "A longer system prompt is prompt-as-fix for an architecture problem; it doesn't change how the model allocates attention.",
    },
  },

  // ─── Multi-Agent Orchestration (Hub & Spoke) ───────────────────────────────
  {
    slug: "multi-agent-task-tool-parallel",
    conceptSlug: "multi-agent-orchestration",
    domain: "Agentic",
    stem: "You're building a research agent with the Claude Agent SDK. A coordinator must fan out 6 independent document-summarization jobs and you want them to run concurrently as isolated subagents. The coordinator's `allowedTools` is `['Read', 'Grep']` and you emit the 6 sub-jobs as six separate sequential assistant turns. Subagents never spawn and the work all runs in one context. What is the correct fix?",
    options: {
      A: "Add `'Task'` to the coordinator's `allowedTools` and emit the six sub-jobs as six `Task` calls in a single assistant response so they run in parallel",
      B: "Increase `max_tokens` so the coordinator has enough output room to spawn all six subagents in one turn and still collect and return every summary",
      C: "Lower the sampling temperature so the coordinator behaves more deterministically and reliably chooses to delegate each of the six jobs to a subagent",
      D: "Pass all six documents in a single prompt and instruct the coordinator to work through and summarize each of them in turn within its own context",
    },
    correctKey: "A",
    distractorReasons: {
      A: "Correct. Spawning subagents requires the `Task` tool in `allowedTools`, and multiple `Task` calls in a single response are what enable parallel subagent execution.",
      B: "`max_tokens` controls output length, not the ability to spawn subagents — the missing `Task` permission is the blocker.",
      C: "Temperature affects sampling, not delegation capability or parallelism; it doesn't explain why subagents never spawn.",
      D: "This abandons the multi-agent design and reintroduces the single-context attention dilution you set out to avoid.",
    },
  },
  {
    slug: "multi-agent-context-delegation",
    conceptSlug: "multi-agent-orchestration",
    domain: "Agentic",
    stem: "A hub-and-spoke coordinator delegates a \"check the deploy config\" subtask to a specialist subagent. To \"be safe,\" the coordinator forwards its entire 80K-token conversation history — every prior subtask, unrelated tool outputs, the full plan — into the subagent's prompt. The subagent's answers are slow, expensive, and increasingly off-topic. What is the best correction?",
    options: {
      A: "Forward even more of the coordinator's context, including the full plan and every prior subtask result, so the subagent has the complete picture first",
      B: "Tell the subagent in its system prompt to simply ignore the parts of the forwarded context that aren't relevant to checking the deploy config",
      C: "Switch the subagent to Opus so it has the capacity to handle the much larger forwarded context without slowing down or drifting off topic",
      D: "Pass the subagent only the explicit, scoped context its subtask needs (the config files and the specific question), not the coordinator's full history",
    },
    correctKey: "D",
    distractorReasons: {
      A: "More context worsens the problem — context pollution is exactly why the subagent is slow, costly, and off-topic.",
      B: "Instructing the model to \"ignore\" noise is soft guidance — the reliable fix is to not send the noise in the first place.",
      C: "A bigger model throws resources at a context-hygiene problem; it doesn't stop the pollution and raises cost further.",
      D: "Correct. Subagents need explicit, scoped context. Dumping the coordinator's full history pollutes their context and degrades focus, speed, and cost.",
    },
  },
  {
    slug: "multi-agent-decomposition-gaps",
    conceptSlug: "multi-agent-orchestration",
    domain: "Agentic",
    stem: "A coordinator splits \"audit this 12-file service for security issues\" into 12 subagents — one per file — each told only \"report vulnerabilities in your file.\" Every per-file report comes back clean, yet a real bug ships: a token minted in `auth.ts` is trusted without re-validation in `handler.ts`. What is the root cause and best fix?",
    options: {
      A: "The decomposition is too narrow — per-file workers can't see cross-file interactions, so issues at the seams fall through. Add an integration pass (or overlap scopes) whose job is reasoning about how files interact",
      B: "Switch every subagent to Opus so each one individually has the reasoning capacity to catch even subtle vulnerabilities — though each still only ever sees the single file it was assigned, never how two files interact",
      C: "Add an instruction like \"also look closely for authentication and token-validation bugs\" to every per-file subagent's prompt",
      D: "Decompose even finer — assign one subagent per function instead of per file — on the theory that more granular scopes find more issues",
    },
    correctKey: "A",
    distractorReasons: {
      A: "Correct. Overly narrow per-file decomposition leaves coverage gaps at the seams; cross-file issues need a worker whose scope spans the interaction (an integration pass), not just more isolated workers.",
      B: "A more capable worker still can't see a file it was never given — the gap is the scoping, not worker intelligence.",
      C: "Each worker still sees only one file, so the instruction can't surface an interaction between two files no single worker ever holds together.",
      D: "Finer decomposition widens the seams — more isolated scopes mean more cross-boundary interactions that no worker owns.",
    },
  },
  {
    slug: "multi-agent-fork-session-explore",
    conceptSlug: "multi-agent-orchestration",
    domain: "Agentic",
    stem: "Mid-session, your agent needs to try three competing refactor strategies and compare them, but you must not pollute the main session's context with the two abandoned attempts. Which approach best fits?",
    options: {
      A: "Run all three refactor attempts inline in the main session, then delete the two failed branches from the conversation history once you've picked a winner",
      B: "Spin up three brand-new, unrelated sessions from scratch and manually copy the relevant state back and forth between them as you compare",
      C: "Use `fork_session` to branch the session for each exploratory attempt, keeping the main context clean, and carry forward only the winning result",
      D: "Lower `max_tokens` for the attempts so the two abandoned branches leave a smaller footprint in the main session's context",
    },
    correctKey: "C",
    distractorReasons: {
      A: "Inline exploration pollutes the main context with abandoned work; after-the-fact deletion is brittle and the tokens already influenced the run.",
      B: "Fresh unrelated sessions lose the shared base context and force error-prone manual state copying; forking preserves the base cheaply.",
      C: "Correct. `fork_session` branches from the current state for isolated exploration, so abandoned attempts never pollute the main session — you merge back only what you keep.",
      D: "Smaller outputs still land in the main context; footprint size isn't the issue — isolation is.",
    },
  },

  // ─── Session Management & Workflows ────────────────────────────────────────
  {
    slug: "session-resume-vs-fork",
    conceptSlug: "session-management",
    domain: "Agentic",
    stem: "A long-running migration agent crashed overnight after 40 tool calls. You want to continue tomorrow exactly where it left off — same accumulated context — and you also want each migration tracked under a stable, findable identifier. Which combination is correct?",
    options: {
      A: "Start a fresh session and paste a written summary of yesterday's 40 tool calls into the system prompt to re-establish the context",
      B: "Use `--resume` to continue the existing (named) session with its preserved context, relying on the named session to locate it",
      C: "Use `fork_session` to branch a brand-new exploration from scratch and pick the migration back up inside that fork",
      D: "Increase the iteration cap and simply re-run the whole migration over again from the very beginning to be safe",
    },
    correctKey: "B",
    distractorReasons: {
      A: "Starting fresh loses the exact accumulated context this scenario requires preserving — prefer fresh + summary only when prior tool results are stale, which is not the case here.",
      B: "Correct. `--resume` continues a prior session with its context intact, and a named session gives you the stable identifier to find and resume it.",
      C: "`fork_session` is for branching parallel exploration without polluting the main line — not for resuming the same work where it stopped.",
      D: "Re-running from the start discards 40 calls of progress and wastes cost; the goal is to continue, not restart.",
    },
  },
  {
    slug: "session-stale-context",
    conceptSlug: "session-management",
    domain: "Agentic",
    stem: "An agent has run for 6 hours across 300 turns. It begins citing a config value that was true early in the session but was changed by a tool call two hours ago, producing confidently wrong recommendations. What is the root-cause-aligned fix?",
    options: {
      A: "Trust the model to notice the newer value on its own, since the updated value is technically still present somewhere in the long context window from the tool call two hours ago",
      B: "Add an instruction like \"always use the most recent value\" to the system prompt and rely on it to override any stale facts still sitting in context",
      C: "Raise the temperature so the model is more likely to consider the alternative, more recent value when it answers",
      D: "Detect and mitigate stale context — compact/refresh the session so superseded facts are re-grounded (e.g., re-read current state) instead of relying on buried early-session text",
    },
    correctKey: "D",
    distractorReasons: {
      A: "Long sessions accumulate stale context the model anchors on; assuming it self-corrects is the very failure mode here.",
      B: "A prompt instruction can't reach back and refresh buried, superseded context — you must re-ground the state, not just ask nicely.",
      C: "Temperature changes sampling randomness, not which facts are current; it won't reliably surface the updated value.",
      D: "Correct. The fix is active stale-context management — detect drift and re-ground current state (compaction / fresh read) so superseded facts don't drive answers.",
    },
  },
  {
    slug: "session-chaining-vs-dynamic",
    conceptSlug: "session-management",
    domain: "Agentic",
    stem: "You're designing two workflows. Workflow A: invoice OCR → extract fields → validate → store (the same fixed steps every time). Workflow B: an open-ended incident-investigation agent whose next step depends entirely on what the previous step found. How should you structure each?",
    options: {
      A: "Use dynamic adaptive decomposition for both workflows, on the principle that maximum flexibility is always the safer default choice",
      B: "Use a static, fixed prompt chain for both workflows, since fixed chains are simpler to build, test, and debug",
      C: "Use a fixed prompt chain for A (predictable, fixed steps) and dynamic adaptive decomposition for B (next step depends on findings)",
      D: "Merge both workflows into a single mega-prompt and let the model figure out the entire control flow on its own",
    },
    correctKey: "C",
    distractorReasons: {
      A: "Dynamic decomposition adds cost and nondeterminism that a fixed, predictable pipeline like A doesn't need.",
      B: "A static chain can't handle B, where the path isn't known in advance — forcing a fixed sequence breaks on the first branch.",
      C: "Correct. Predictable fixed-step tasks fit prompt chaining; tasks whose next step depends on prior findings need dynamic adaptive decomposition.",
      D: "A single mega-prompt loses the structure and observability of explicit steps and still doesn't solve B's need to adapt.",
    },
  },

  // ─── Agentic Loop & Core API (tool-result appending, SDK control flow) ──────
  {
    slug: "agentic-loop-tool-result-append",
    conceptSlug: "agentic-loop-termination",
    domain: "Agentic",
    stem: "You're hand-implementing an agentic loop. After the model returns a `tool_use` block, your code runs the tool but then sends the next request containing only the original user message plus the tool's raw output as a new user string — it does NOT append the assistant's `tool_use` block and a matching `tool_result` block to the running messages array. The model keeps re-requesting the same tool. What's wrong?",
    options: {
      A: "Each iteration must append the assistant `tool_use` turn AND a corresponding `tool_result` block to the conversation, then resend the full messages array so the model sees its call was satisfied",
      B: "You must lower `max_tokens` so the model has less room to keep repeating the same tool call over and over on every successive turn",
      C: "Switch to a more capable model like Opus, on the assumption that a stronger model will simply remember it already called the tool and move on",
      D: "Add an explicit instruction like \"do not repeat tool calls you have already made\" to the system prompt so it won't call the same tool twice",
    },
    correctKey: "A",
    distractorReasons: {
      A: "Correct. The loop advances by appending the assistant's `tool_use` and the matching `tool_result` each iteration; without that linkage the model never sees its call as fulfilled and re-requests it.",
      B: "`max_tokens` limits output length; it has nothing to do with the missing `tool_result` linkage causing the repeat.",
      C: "A bigger model can't compensate for a malformed conversation that omits the `tool_result` it needs to proceed.",
      D: "Prompt instructions can't substitute for the structured `tool_use`/`tool_result` round-trip the API requires to advance the loop.",
    },
  },
  {
    slug: "agentic-loop-sdk-control-flow",
    conceptSlug: "agentic-loop-termination",
    domain: "Agentic",
    stem: "A teammate using the Claude Agent SDK writes a manual `while` loop that, after each response, parses the assistant's prose for the word \"finished\" to decide whether to stop, and re-implements tool dispatch by hand — even though the SDK already runs the agentic loop. What is the most accurate guidance?",
    options: {
      A: "Hand-rolling the loop is required here, since the Agent SDK only ever sends and returns a single message at a time",
      B: "Set `tool_choice: any` so that the loop is given a clear and reliable signal for when it should stop iterating",
      C: "Keep the prose parsing for the word \"finished\" but also check `stop_reason` as a secondary confirmation signal",
      D: "Let the SDK drive the loop — it dispatches tools and continues while `stop_reason` is `tool_use`, terminating on `end_turn`; you supply tools and a backstop iteration cap, not prose-parsing",
    },
    correctKey: "D",
    distractorReasons: {
      A: "The Agent SDK manages the loop — tool dispatch and continuation — so reimplementing it by hand is unnecessary and error-prone.",
      B: "`tool_choice: any` forces the model to call some tool; it has nothing to do with detecting termination and would actually prevent stopping.",
      C: "Keeping prose-parsing keeps the bug — the structured `stop_reason` is the authority and should replace text inspection entirely, not supplement it.",
      D: "Correct. The SDK continues while `stop_reason` is `tool_use` and stops on `end_turn`; your job is to register tools and optionally cap iterations, not to parse text.",
    },
  },

  // ─── Guardrails (PostToolUse normalization + escalation-signal anti-patterns) ─
  {
    slug: "guardrails-posttooluse-normalize",
    conceptSlug: "guardrails",
    domain: "Agentic",
    stem: "A `lookup_customer` tool returns phone numbers in a dozen inconsistent formats from different backends, and downstream tools choke on the variance. You want every phone number normalized to E.164 before the model or any other tool ever sees it, deterministically. Which mechanism fits best?",
    options: {
      A: "A `PostToolUse` hook that intercepts `lookup_customer` output and rewrites phone numbers to E.164 before they re-enter the conversation",
      B: "Add an instruction to the system prompt telling the model that it should always normalize every phone number it sees into the standard E.164 format",
      C: "A `PreToolUse` hook on `lookup_customer` that tries to normalize the phone numbers before the tool actually runs",
      D: "Ask the model to remember to call a separate `normalize_phone` tool after each `lookup_customer` call completes",
    },
    correctKey: "A",
    distractorReasons: {
      A: "Correct. `PostToolUse` hooks intercept and modify a tool's output for deterministic data normalization before it re-enters the conversation.",
      B: "A system-prompt instruction is probabilistic guidance — it will drift and won't guarantee every number is normalized.",
      C: "`PreToolUse` fires before the tool executes, so the output to normalize doesn't exist yet — wrong point in the lifecycle.",
      D: "Depending on the model to remember a follow-up tool call is non-deterministic; a hook enforces normalization unconditionally.",
    },
  },
  {
    slug: "guardrails-confidence-escalation",
    conceptSlug: "guardrails",
    domain: "Agentic",
    stem: "A support agent must escalate hard tickets to a human. A proposal: ask the model to self-report a confidence score (0–1) and escalate when confidence < 0.6. In testing, the model reports 0.9 on tickets it then answers incorrectly and 0.4 on tickets it handles fine. What's the architecturally sound escalation trigger?",
    options: {
      A: "Keep the self-reported confidence score but recalibrate the escalation threshold upward, from 0.6 to around 0.75",
      B: "Escalate on deterministic, observable signals — a hook detecting a refund over a hard limit, repeated failed resolution attempts, or an explicit policy-matched category — not the model's self-reported confidence",
      C: "Ask the model to rate its own confidence twice on each ticket and escalate based on the average of the two scores",
      D: "Add an instruction like \"be honest and well-calibrated about your confidence\" to the system prompt and trust it",
    },
    correctKey: "B",
    distractorReasons: {
      A: "Model self-reported confidence is unreliable (it's high on wrong answers here); no threshold fixes a signal that doesn't track correctness.",
      B: "Correct. Escalation should hinge on deterministic, observable triggers (hard limits, failed-attempt counts, policy categories), not an unreliable self-estimate.",
      C: "Averaging two unreliable self-estimates yields another unreliable number — it still doesn't track correctness.",
      D: "Prompting for honesty can't make a model's confidence calibrated; the signal itself is the problem, not its phrasing.",
    },
  },
  {
    slug: "guardrails-sentiment-escalation",
    conceptSlug: "guardrails",
    domain: "Agentic",
    stem: "To decide which tickets need a senior human, a team proposes escalating any ticket where a sentiment classifier flags the customer as \"angry.\" In testing, a calm customer with a complex tax-compliance question is handled by the bot and gets it wrong, while an angry customer with a trivial password reset is escalated. What's the flaw and the better design?",
    options: {
      A: "Escalate every single ticket straight to a senior human to be safe, rather than attempting to triage them at all",
      B: "Tune and retrain the sentiment classifier so that it detects customer anger far more accurately than it does today",
      C: "Sentiment is a poor proxy for complexity; escalate on complexity/risk signals (policy category, required privileges, dollar thresholds, repeated failures) and treat sentiment as at most one minor input",
      D: "Add several examples of angry customer messages to the system prompt so the model learns to escalate that kind of ticket",
    },
    correctKey: "C",
    distractorReasons: {
      A: "Escalating everything erases the triage value and overloads humans; the goal is to route by genuine complexity/risk.",
      B: "Even a perfect anger detector misroutes, because the two failing cases prove sentiment doesn't track what actually needs a human.",
      C: "Correct. Sentiment does not equal complexity or risk — route on complexity/risk signals. The calm-but-complex and angry-but-trivial cases show why sentiment misroutes.",
      D: "More prompt examples still optimize for the wrong signal (sentiment) instead of complexity/risk.",
    },
  },

  // ─── Domain 3: Claude Code Configuration & Workflows ────────────────────────
  {
    slug: "claude-md-path-rules",
    conceptSlug: "claude-md-rules",
    domain: "Claude Code",
    stem: "Your codebase has distinct conventions per area: React components use hooks, API handlers use async/await with specific error handling, and DB models follow a repository pattern. Test files live beside the code they test (e.g. `Button.test.tsx` next to `Button.tsx`) all over the tree, and every test must follow the same conventions regardless of location. What's the most maintainable way to make Claude apply the right conventions automatically?",
    options: {
      A: "Create rule files in `.claude/rules/` with YAML frontmatter `paths` glob patterns so conventions load conditionally by file path",
      B: "Consolidate every convention into the root CLAUDE.md under per-area headers and rely on Claude to infer which section applies",
      C: "Create one skill per code area in `.claude/skills/`, each carrying that area's conventions in its SKILL.md body",
      D: "Place a separate CLAUDE.md in each subdirectory containing that directory's specific conventions",
    },
    correctKey: "A",
    distractorReasons: {
      A: "Correct. Path-scoped rules (`paths: [\"**/*.test.tsx\"]`) apply conventions by file pattern regardless of directory — exactly what spread-out test files need.",
      B: "Relying on inference from headers is unreliable; nothing guarantees the right section is applied to the right file.",
      C: "Skills are invoked on demand for workflows — they aren't deterministically loaded by file path, so 'automatic' application isn't guaranteed.",
      D: "Directory-bound CLAUDE.md files can't follow a convention that cuts across many directories; you'd duplicate the test rules everywhere.",
    },
  },
  {
    slug: "plan-mode-vs-direct",
    conceptSlug: "skills-commands-planmode",
    domain: "Claude Code",
    stem: "You've been assigned to restructure a monolithic application into microservices — changes across dozens of files plus decisions about service boundaries and module dependencies. Which approach should you take in Claude Code?",
    options: {
      A: "Enter plan mode to explore the codebase, understand dependencies, and design the approach before making any changes",
      B: "Start in direct execution and make changes incrementally, letting the implementation reveal the natural service boundaries",
      C: "Use direct execution with comprehensive upfront instructions describing exactly how every service should be structured",
      D: "Begin in direct execution and switch to plan mode only if you hit unexpected complexity during implementation",
    },
    correctKey: "A",
    distractorReasons: {
      A: "Correct. Plan mode is built for large-scale, multi-file, architectural work — safe exploration and design before committing to changes.",
      B: "Discovering dependencies mid-rewrite is how you buy expensive rework; the boundaries should be designed, not stumbled into.",
      C: "Comprehensive upfront instructions assume you already know the right structure — without exploring the code, you don't.",
      D: "The complexity is already stated in the task (architecture, dozens of files); deferring plan mode ignores what you know now.",
    },
  },
  {
    slug: "cicd-print-flag",
    conceptSlug: "cicd-refinement",
    domain: "Claude Code",
    stem: "Your CI script runs `claude \"Review this pull request for security issues\"` but the job hangs indefinitely — logs show Claude Code waiting for interactive input. What's the correct fix for automated pipelines?",
    options: {
      A: "Add the `-p` (print) flag: `claude -p \"Review this pull request for security issues\"`",
      B: "Set `CLAUDE_HEADLESS=true` in the pipeline environment before invoking the command",
      C: "Redirect stdin from /dev/null so the process can't block on input: `claude \"...\" < /dev/null`",
      D: "Add the `--batch` flag so Claude Code queues the prompt and exits when processing completes",
    },
    correctKey: "A",
    distractorReasons: {
      A: "Correct. `-p` / `--print` is the documented non-interactive mode: process the prompt, write to stdout, exit — what CI requires.",
      B: "There is no `CLAUDE_HEADLESS` environment variable; this feature doesn't exist.",
      C: "A Unix workaround that doesn't engage Claude Code's actual non-interactive mode; behavior remains undefined.",
      D: "There is no `--batch` flag in the Claude Code CLI.",
    },
  },
  // ─── Domain 4: Batch processing ──────────────────────────────────────────────
  {
    slug: "batch-api-latency-fit",
    conceptSlug: "batch-extraction-quality",
    domain: "Prompts",
    stem: "Real-time Claude calls currently power two workflows: (1) a blocking pre-merge check developers wait on, and (2) a technical-debt report generated overnight. Your manager proposes moving both to the Message Batches API for its 50% cost savings. How should you evaluate this?",
    options: {
      A: "Move only the overnight report to batch processing; keep the pre-merge check on the synchronous API",
      B: "Move both to batch with status polling, since batches usually finish much faster than the 24-hour ceiling",
      C: "Keep both on real-time calls because batch results come back unordered and can't be matched to requests",
      D: "Move both to batch with a timeout that falls back to a real-time call whenever a batch runs long",
    },
    correctKey: "A",
    distractorReasons: {
      A: "Correct. Batch trades latency (up to 24h, no SLA) for 50% savings — ideal for overnight reports, unacceptable for a check developers block on.",
      B: "'Usually faster' is not a guarantee; a blocking workflow can't rest on a no-SLA processing window.",
      C: "A misconception — batch responses correlate to requests via `custom_id`; ordering is a non-issue.",
      D: "Needless complexity that still makes developers wait out the timeout; the clean fix is matching each workflow to the right API.",
    },
  },
  // ─── Domain 2: Structured errors ─────────────────────────────────────────────
  {
    slug: "structured-error-taxonomy",
    conceptSlug: "tool-interface-errors",
    domain: "Tool & MCP",
    stem: "Every tool on your MCP server returns the string \"Operation failed.\" on any failure — timeouts, invalid input, and policy violations alike. The agent retries policy-violation failures in a loop and gives up immediately on transient timeouts. What change most effectively fixes this behavior?",
    options: {
      A: "Return structured error metadata: an `errorCategory` (transient/validation/business/permission), an `isRetryable` boolean, and a human-readable description",
      B: "Add a system prompt instruction telling the agent to think carefully about whether each failure is worth retrying",
      C: "Set a global cap of three retries per tool so the policy-violation loop can never run more than three times",
      D: "Switch the agent to a more capable model that can infer the likely failure cause from surrounding context",
    },
    correctKey: "A",
    distractorReasons: {
      A: "Correct. The agent can only make good recovery decisions from structured error context — category and retryability tell it to retry timeouts and stop on policy violations.",
      B: "The agent has no signal to reason over — every failure looks identical; instruction quality can't fix missing information.",
      C: "A cap bounds the damage but fixes neither the wasted retries on business errors nor the premature give-up on transient ones.",
      D: "No model can reliably infer error class from a string that carries no class information.",
    },
  },
  // ─── Domain 5: Provenance ────────────────────────────────────────────────────
  {
    slug: "provenance-conflicting-sources",
    conceptSlug: "error-propagation-provenance",
    domain: "Context",
    stem: "Your research system's document-analysis subagent finds two credible industry reports stating different market sizes — one collected data in 2023, the other in 2025. The synthesis agent currently picks the larger figure and drops the other. What should happen instead?",
    options: {
      A: "Include both figures, each annotated with source attribution and data-collection date, and let the report distinguish them rather than silently choosing",
      B: "Use the more recent figure and discard the older one, since fresher data supersedes stale data",
      C: "Average the two figures so the report presents a single number that reflects both sources",
      D: "Send the search subagent back out repeatedly until it finds a third source that breaks the tie",
    },
    correctKey: "A",
    distractorReasons: {
      A: "Correct. Conflicting credible values get annotated with attribution and dates — temporal differences are context, not contradictions, and the reader needs both.",
      B: "Recency alone doesn't invalidate the earlier figure (different methodology/scope may explain it); silently discarding loses provenance.",
      C: "An average is a number neither source reported — it fabricates a statistic and destroys attribution.",
      D: "A third source doesn't resolve a difference that may be methodological or temporal; it delays the report and may still conflict.",
    },
  },
  // ─── Proportionality pair: prompt-level fixes that ARE correct ───────────────
  {
    slug: "tool-selection-descriptions-first",
    conceptSlug: "tool-interface-errors",
    domain: "Tool & MCP",
    stem: "Production logs show your agent frequently calls `get_customer` when users ask about orders (\"check my order #12345\") instead of `lookup_order`. Both tools have one-line descriptions (\"Retrieves customer information\" / \"Retrieves order details\") and accept similar identifier formats. What's the most effective FIRST step?",
    options: {
      A: "Add 5–8 few-shot examples to the system prompt demonstrating order queries routing to `lookup_order`",
      B: "Expand each tool's description to cover input formats, example queries, edge cases, and when to use it versus the similar tool",
      C: "Build a routing layer that parses user input each turn and pre-selects the appropriate tool from detected keywords",
      D: "Consolidate both into a single `lookup_entity` tool that accepts any identifier and picks the backend internally",
    },
    correctKey: "B",
    distractorReasons: {
      A: "Few-shot adds token overhead while leaving the root cause — undifferentiated descriptions — in place.",
      B: "Correct. Descriptions are the primary tool-selection mechanism; enriching them is the low-effort, high-leverage fix that addresses the root cause. The routing-layer and consolidation options are the over-engineered distractors here.",
      C: "Over-engineered — it bypasses the model's language understanding and adds a brittle keyword layer before simpler fixes were tried.",
      D: "A real architectural option, but far more effort than a first step warrants when the immediate defect is description quality.",
    },
  },
  {
    slug: "escalation-criteria-prompt-first",
    conceptSlug: "guardrails",
    domain: "Agentic",
    stem: "Your support agent hits 55% first-contact resolution against an 80% target. Logs show it escalates straightforward cases (standard damage replacements with photo evidence) while attempting complex policy-exception cases itself. What most effectively improves its escalation calibration?",
    options: {
      A: "Add explicit escalation criteria to the system prompt with few-shot examples showing when to escalate versus resolve autonomously",
      B: "Have the agent self-report a confidence score before each response and auto-route to humans below a threshold",
      C: "Train a separate classifier on historical tickets to predict which requests need escalation before the agent runs",
      D: "Add sentiment analysis and escalate automatically whenever customer frustration crosses a threshold",
    },
    correctKey: "A",
    distractorReasons: {
      A: "Correct. The root cause is unclear decision boundaries — explicit criteria plus few-shot examples is the proportionate fix. This is criteria definition, not prompt-as-enforcement: nothing here needs a deterministic guarantee, it needs better judgment.",
      B: "Self-reported confidence is poorly calibrated — this agent is already confidently wrong on the hard cases.",
      C: "Over-engineered: labeled data and ML infrastructure before prompt-level criteria have even been tried.",
      D: "Sentiment doesn't track case complexity — calm customers bring hard problems and angry ones bring trivial ones.",
    },
  },

  // ─── Practice-exam remediation: targeted loophole questions ─────────────────
  // Built from the practice-exam misses. The dominant failure is the "few-shot
  // reflex" — reaching for examples/confidence-display when the correct lever is
  // explicit criteria, a renamed description, a hook, or honoring a constraint.
  {
    slug: "partial-results-coverage-annotation",
    conceptSlug: "error-propagation-provenance",
    domain: "Context",
    stem: "A multi-source research agent asked its document-analysis subagent for findings across five regulatory regimes, but only three returned — two source databases were down. The subagent currently throws an error and the coordinator aborts the whole report, even though stakeholders would still value a partial one. What should the subagent do instead?",
    options: {
      A: "Return findings for the three available regimes plus a coverage annotation marking the other two as gaps from unavailable sources, so synthesis proceeds with transparency",
      B: "Return a hard error so the coordinator retries the entire five-regime query from scratch until every source succeeds",
      C: "Return the three retrieved regimes marked as a complete result so the report looks finished",
      D: "Fill the two missing regimes with the closest available regime's data so every slot has a value",
    },
    correctKey: "A",
    distractorReasons: {
      A: "Correct. Partial upstream results are passed forward with explicit coverage annotations (well-supported vs gaps) — graceful degradation with transparency preserves completed work and surfaces uncertainty.",
      B: "Aborting and retrying everything discards three regimes of good work and may never finish while the two databases stay down.",
      C: "Marking a partial result as complete hides the gaps; downstream consumers decide on data they wrongly believe is comprehensive.",
      D: "Imputing one regime's data for another fabricates coverage and corrupts the findings — a missing regime is a gap, not a value to substitute.",
    },
  },
  {
    slug: "tool-overlap-rename-descriptions",
    conceptSlug: "tool-interface-errors",
    domain: "Tool & MCP",
    stem: "Your research agent has two tools — `analyze_content` (intended for web-page results) and `analyze_document` (intended for uploaded files) — and both descriptions read \"Analyzes content and returns key points.\" The agent routinely sends uploaded PDFs to `analyze_content`. What most effectively fixes the misrouting?",
    options: {
      A: "Rename `analyze_content` to `extract_web_results` and rewrite both descriptions to state their distinct inputs, outputs, and when to use each versus the other",
      B: "Add few-shot examples to the system prompt showing PDFs routed to `analyze_document`",
      C: "Lower the model's temperature so it selects tools more deterministically",
      D: "Merge both into a single `analyze` tool that inspects the input and routes internally",
    },
    correctKey: "A",
    distractorReasons: {
      A: "Correct. Misrouting between near-identical tools is a description problem — disambiguating names and descriptions (distinct inputs/outputs/boundaries) fixes the signal the model actually selects on.",
      B: "Few-shot patches the shown cases but leaves the ambiguous descriptions in place, so novel phrasings keep misrouting.",
      C: "Temperature changes sampling randomness, not the semantic ambiguity between two tools that describe themselves identically.",
      D: "Consolidation is a heavier redesign than the defect warrants and buries the routing decision in opaque tool logic instead of making each tool's purpose clear.",
    },
  },
  {
    slug: "criteria-over-fewshot-decision-boundary",
    conceptSlug: "prompt-engineering",
    domain: "Prompts",
    stem: "Your code-review agent flags far too many comment/docstring issues — it reports any comment that isn't perfectly precise. The current instruction is \"check that comments are accurate.\" You need it to flag only genuinely misleading comments without missing real ones. What most effectively fixes this?",
    options: {
      A: "Replace the vague instruction with an explicit criterion: flag a comment only when its claimed behavior contradicts what the code actually does",
      B: "Add few-shot examples of misleading comments so the model learns to recognize similar ones",
      C: "Instruct the model to \"be conservative and only report high-confidence comment issues\"",
      D: "Have the model attach a confidence score to each comment finding and drop everything below 0.8",
    },
    correctKey: "A",
    distractorReasons: {
      A: "Correct. The failure is an undefined decision boundary — a specific categorical criterion ('claimed behavior contradicts actual behavior') states exactly what counts as an issue, fixing false positives and false negatives together.",
      B: "Few-shot teaches the shown patterns but never defines the underlying criterion, so it won't generalize to novel kinds of misleading comments.",
      C: "'Be conservative' is vague guidance that doesn't change what the model treats as an issue; it suppresses volume unpredictably without improving precision.",
      D: "A confidence cutoff filters on the model's own uncalibrated self-rating instead of defining what a genuine issue is — it hides findings rather than sharpening the boundary.",
    },
  },
  {
    slug: "fewshot-for-output-format",
    conceptSlug: "prompt-engineering",
    domain: "Prompts",
    stem: "Your review agent identifies the right issues, but its output shape is wildly inconsistent — sometimes a paragraph, sometimes a bullet, often missing the file location or the suggested fix. More detailed written instructions about the format haven't made it consistent. What most effectively fixes the formatting?",
    options: {
      A: "Add 3–4 few-shot examples showing the exact output shape you want: location, issue, severity, suggested fix",
      B: "Write a longer, more detailed prose specification of the required format in the system prompt",
      C: "Define an explicit categorical criterion for what counts as a reportable issue",
      D: "Lower the temperature so the output is more deterministic",
    },
    correctKey: "A",
    distractorReasons: {
      A: "Correct. Few-shot examples are the most effective lever for consistent OUTPUT FORMAT when prose alone varies — a few concrete examples of the exact shape give the model a pattern to match.",
      B: "More prose is what already failed; format consistency comes from showing the shape, not describing it at greater length.",
      C: "Defining what counts as an issue fixes selection, not formatting — the agent already picks the right issues; only their presentation varies.",
      D: "Lower temperature trims wording variance slightly but won't impose a missing structure like a required location or fix field.",
    },
  },
  {
    slug: "ci-no-filter-inline-reasoning",
    conceptSlug: "cicd-refinement",
    domain: "Claude Code",
    stem: "Your CI code review posts ~15 findings per pull request and developers complain triage takes too long. A hard team requirement: no findings may be filtered out or hidden before a developer sees them. How do you cut triage time without violating that constraint?",
    options: {
      A: "Require the review to include its reasoning and a confidence assessment inline with each finding so developers can evaluate each at a glance",
      B: "Surface only the findings the review rates high-confidence and hold back the uncertain ones",
      C: "Cap the review at the five most severe findings per pull request",
      D: "Raise the internal severity threshold so fewer findings qualify to be reported",
    },
    correctKey: "A",
    distractorReasons: {
      A: "Correct. The constraint forbids removing findings, so the lever is making each faster to judge — inline reasoning and confidence speeds triage while every finding stays visible.",
      B: "Holding back low-confidence findings is filtering before review, which the stated requirement explicitly forbids.",
      C: "Capping to five drops findings the developer is required to see — a direct constraint violation.",
      D: "Raising the threshold so fewer findings 'qualify' is filtering by another name; the requirement is that nothing is removed before review.",
    },
  },
  {
    slug: "ci-disable-noisy-category",
    conceptSlug: "cicd-refinement",
    domain: "Claude Code",
    stem: "Your CI review reports across several categories. Style, naming, and documentation findings have a high false-positive rate; security and correctness findings are accurate. Developers have started ignoring ALL findings — including the accurate ones — because of the noise. What's the most effective response?",
    options: {
      A: "Temporarily disable the high-false-positive categories, keep running the high-precision ones, and re-enable each noisy category only after improving its prompt",
      B: "Keep all categories but attach a confidence score to every finding and let developers decide which to investigate",
      C: "Switch to a more capable model so the noisy categories become more accurate",
      D: "Add an instruction telling the model to be more careful in the style, naming, and documentation categories",
    },
    correctKey: "A",
    distractorReasons: {
      A: "Correct. The damage is eroded trust from noise; removing the noisy categories immediately restores trust in the accurate ones, and their prompts are improved before re-enabling.",
      B: "Confidence scores shift the triage burden onto developers who already distrust the system and won't trust its self-ratings either — the noise is still there.",
      C: "A bigger model is an expensive gamble that doesn't structurally remove the noise currently destroying trust in every finding.",
      D: "'Be more careful' is vague guidance that won't reliably lower those categories' false-positive rate.",
    },
  },
  {
    slug: "batch-no-midrequest-tool-calling",
    conceptSlug: "batch-extraction-quality",
    domain: "Prompts",
    stem: "You want to move a deep code-review workflow to the Message Batches API for the cost savings. The workflow is iterative: the model analyzes a file, calls a tool to fetch a dependency, gets the result, and continues reasoning within the same logical task. Why is this a poor fit for the batch API?",
    options: {
      A: "The batch API's asynchronous model can't execute a tool mid-request and feed the result back for the model to continue — it breaks multi-round tool-calling within one interaction",
      B: "The batch API can't correlate each response to its request, so you couldn't tell which result belongs to which file",
      C: "The batch API supports only a single model and can't run the deeper-reasoning configuration this review needs",
      D: "The batch API rejects any request that includes a JSON output schema",
    },
    correctKey: "A",
    distractorReasons: {
      A: "Correct. Batch is fire-and-forget and asynchronous — there's no way to run a tool mid-request and return its result for the model to continue, which is exactly what an iterative tool-calling workflow needs.",
      B: "Correlation is a non-issue — the batch API matches responses to requests via `custom_id`.",
      C: "The batch API doesn't restrict you to one model or configuration; model choice is unaffected.",
      D: "The batch API accepts JSON output schemas; structured output is not the limitation.",
    },
  },
  {
    slug: "csr-prerequisite-gate-hook",
    conceptSlug: "guardrails",
    domain: "Agentic",
    stem: "Your customer-support agent must NEVER issue a refund before identity is verified via `get_customer`. In production, 12% of the time it calls `process_refund` using only a name the customer typed, occasionally refunding the wrong account. What most reliably enforces the ordering?",
    options: {
      A: "Add a programmatic prerequisite that blocks `process_refund` until `get_customer` has returned a verified customer ID for the session",
      B: "Add a line to the system prompt stating that identity verification is mandatory before any refund",
      C: "Add few-shot examples showing the agent always calling `get_customer` before `process_refund`",
      D: "Reorder the tool definitions so `get_customer` appears before `process_refund` in the tool list",
    },
    correctKey: "A",
    distractorReasons: {
      A: "Correct. A hard ordering rule with financial consequences needs deterministic enforcement — a programmatic prerequisite gate guarantees it, which prompt-level approaches cannot.",
      B: "A system-prompt rule is probabilistic guidance; at scale it is skipped some fraction of the time, and refunding the wrong account is unacceptable.",
      C: "Few-shot raises compliance but never guarantees it — the model can still skip the step on inputs unlike the examples.",
      D: "Tool ordering in the list doesn't constrain call sequence; the model can still call the refund tool first.",
    },
  },
];
